# Generated by Django 5.2.3 on 2025-06-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_usagerpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CibleExperimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('seniors', 'Seniors'), ('professionnels', 'Professionnels'), ('aidants', 'Aidants')], max_length=20)),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='gestion.experimentationgenerale')),
            ],
        ),
        migrations.CreateModel(
            name='StatutCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_statut', models.CharField(max_length=100)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='gestion.cibleexperimentation')),
            ],
        ),
        migrations.CreateModel(
            name='ChampStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=100)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='gestion.statutcible')),
            ],
        ),
    ]
