# Generated by Django 5.2.3 on 2025-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_cibleexperimentation_statutcible_champstatut'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagerRI2S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_usager', models.CharField(choices=[('pro', 'Professionnel'), ('non_pro', 'Non professionnel')], max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('structure', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usagerpro',
            options={},
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='remarques',
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='usagerpro',
            name='telephone',
        ),
        migrations.AddField(
            model_name='usagerpro',
            name='cible',
            field=models.CharField(choices=[('seniors', 'Seniors'), ('aidants', 'Aidants'), ('professionnels', 'Professionnels')], default='seniors', max_length=30),
        ),
        migrations.AlterField(
            model_name='usagerpro',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usagerpro',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
