# Generated by Django 5.2.3 on 2025-06-19 08:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_champpersonnalise_titre_section_champstatut_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerri2s',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='ChampCommun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_section', models.CharField(default='Section commune', max_length=255)),
                ('nom_champ', models.CharField(max_length=255)),
                ('type_champ', models.CharField(choices=[('text', 'Texte'), ('date', 'Date'), ('number', 'Nombre'), ('file', 'Fichier'), ('select', 'Liste déroulante')], max_length=50)),
                ('valeurs_possibles', models.TextField(blank=True)),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs_communs', to='gestion.experimentationgenerale')),
            ],
        ),
    ]
