# Generated by Django 5.2.3 on 2025-06-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_usagerri2s_role_champcommun'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaireExperimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=100)),
                ('experimentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.experimentationgenerale')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usagerri2s')),
            ],
        ),
    ]
