# Generated by Django 5.2.3 on 2025-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_beneficiaireexperimentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerpro',
            name='sexe',
            field=models.CharField(default='text', max_length=10),
            preserve_default=False,
        ),
    ]
