# Generated by Django 5.2.3 on 2025-06-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_usagerpro_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeurChampCommun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=255)),
                ('valeur', models.TextField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_champs_communs', to='gestion.beneficiaireexperimentation')),
            ],
        ),
        migrations.CreateModel(
            name='ValeurChampStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=255)),
                ('valeur', models.TextField()),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_champs_statut', to='gestion.beneficiaireexperimentation')),
            ],
        ),
    ]
